package com.vaultpass.desktop.domain.exportimport

import com.vaultpass.desktop.domain.models.VaultEntry
import kotlinx.serialization.json.add
import kotlinx.serialization.json.addJsonObject
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import kotlinx.serialization.json.putJsonArray

/**
 * Serializes domain VaultEntry models into the exact simplified JSON format generated by Android VaultPass.
 * 100% compatible with Android VaultPass JSON import.
 */
object JsonExporter {
    fun format(entries: List<VaultEntry>): String {
        val titleCounts = mutableMapOf<String, Int>()

        val rootObj = buildJsonObject {
            for (entry in entries) {
                var finalTitle = entry.title
                var count = titleCounts[finalTitle] ?: 0
                if (count > 0) {
                    do {
                        count++
                        finalTitle = "${entry.title} ($count)"
                    } while (titleCounts.containsKey(finalTitle))
                }
                titleCounts[finalTitle] = count.takeIf { it > 0 } ?: 1

                putJsonArray(finalTitle) {
                    add(entry.username)
                    add(entry.secret)

                    val hasMetadata = entry.isFavorite || entry.url.isNotEmpty() || entry.notes.isNotEmpty() || entry.tags.isNotEmpty() || (!entry.category.isNullOrEmpty() && entry.category != "Personal")

                    if (hasMetadata) {
                        addJsonObject {
                            if (entry.isFavorite) put("isFavorite", true)
                            if (entry.url.isNotEmpty()) put("website", entry.url)
                            if (!entry.category.isNullOrEmpty() && entry.category != "Personal") put("category", entry.category)
                            if (entry.notes.isNotEmpty()) put("notes", entry.notes)
                            if (entry.tags.isNotEmpty()) {
                                putJsonArray("tags") { entry.tags.forEach { add(it) } }
                            }
                        }
                    }
                }
            }
        }
        return rootObj.toString()
    }
}
